__title__ = "Gitlab Siphon"
__version__ = "0.1.4"
__author__ = "Gabriel Creti"
__license__ = "Apache"
__copywrite__ = "Copyright (C) 2022 Gabriel Creti <gabrielcreti@gmail.com>"
__email__ = "gabrielcreti@gmail.com"
__status__ = "Development"
